version: '3.9'

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_URL=postgresql://postgres:postgres@flask_db:5433/postgres
    depends_on:
      - flask_db

  flask_db:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
